-- Database init

-- Create tables from scratch
DROP TABLE IF EXISTS "jokes";
CREATE TABLE "jokes" (`jokeId` INTEGER PRIMARY KEY AUTOINCREMENT,
                      `isUsed` INTEGER NOT NULL,
                      `deliveryTime` INTEGER,
                      `type` TEXT NOT NULL,
                      `jokeText` TEXT NOT NULL);

DROP TABLE IF EXISTS "schedules";
CREATE TABLE "schedules" (`jokeId` INTEGER,
                          `time` INTEGER,
                          FOREIGN KEY(`jokeId`) REFERENCES `jokes`(`jokeId`) );

-- Add jokes to the collection
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Hogy hívják a süket kutyát?\n- ???\n- Hát, jó hangosan!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Ki az állatok diszkósa?\n- ???\n- A technos-béka.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Két tehén nadrágot vásárol a boltban. Mondja az egyik:\n- Bőő!\n- Mondja a másik:\n- Honnan tudod, még fel sem próbáltad!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Áll egy tehén a buszmegállóban. Ha megjön a busz, hova fog felszállni?\n- ???\n- Legelőre.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','A pocok kérdezi a kígyót:\n- Hé, te kígyó, tényleg megetted a haveromat?\n- Mérget vehetsz rá!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Hogy rejtőzik el a gyík a kemencében?\n- ???\n- Beleolvad a környezetébe!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Hogy hívják azt a pávát, amelyik tigrissel találkozik?\n- ???\n- Pápáva.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Mi a különbség a leopárd és a pöttyös labda között?\n- ???\n- A labdába kétszer is nyugodtan bele lehet rúgni.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Miért van akkora füle az elefántnak?\n- ???\n- Hogy könnyebben szállhasson virágról virágra!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Mit mond a horgász, ha megmoccan a vízben az úszója?\n- ???\n- Pszt! Ráng!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Melyik hal tanulna idegen nyelvet?\n- ???\n- Az angolna.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Mit ér az a sirály, amelyik elfelejt repülni?\n- ???\n- Földet!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Mit rágcsál az emberevő hód?\n- ???\n- Családfát.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Miért zsíros a tej?\n- ???\n- Hogy ne nyikorogjon a tehén fejés közben.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Milyenre vágatja a frizuráját a vidra?\n- ???\n- Rövidra!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Mit fűrészel a macska?\n- ???\n- A kutya fáját.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Hogy hívják a portugál madarat?\n- ???\n- Rodrigó');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Hova járnak szórakozni a hernyók?\n- ???\n- Bábszínházba.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Honnan lehet felismerni a vidám elefántot?\n- ???\n- Nem lógatja az orrát.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Mi van a macske fején?\n- ???\n- Cirmos cica haj');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- A sivatagban él és látszólag semm dolga nincs, mi az?\n- ???\n- Ücsörgőkígyó.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Hogyan jut lakáshoz a meztelen csiga?\n- ???\n- Megházasodik.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Melyik a legfeledékenyebb hal?\n- ???\n- Nem emlékszem rája..');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Miből faragják a fatehenet?\n- ???\n- Tőgyfából.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Mi az amiről a kígyók beszélgetnek?\n- ???\n- Szisztéma.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Két hangyász beszélget:\n- Megkóstolod az ebédemet?\n- Na jó, de csak egy katonát..');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Mit csinál a medúza a rock koncerten?\n- ???\n- Az első sorban csápol.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Miről lehet felismerni a repülő nyulat?\n- ???\n- Egy hatalmas sast cipel a hátán.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Miért szeret a fóka a jégen sörözni?\n- ???\n- Mert ott jobban csúszik.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Miért szomorú a hím gólya?\n- ???\n- Mert a nőstényt nem érdekli hogy mennyit költ.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Milyen zene szól a hangyász temetésén?\n- ???\n- A han-gyászinduló.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Mi a különbség a sas és a szálloda közt?\n - Hát a sas az száll ide, száll oda, de a szálloda az nem sas ide, sas oda.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'animal','- Mi lesz a lóból, ha átmegy rajta az úthenger?\n - Sikló.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Két tészta megy a sivatagban. Melyik a zsidó?\n- ???\n- A metélt.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mondj egy selymes, zöld prófétát!\n- ???\n- Mohamed.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mi a hasonlóság a szexben és a teniszben?\n- ???\n- A teniszben az a lényeg hogy ki szervál, míg a szexben melyik szerv áll!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Hol található sok fekete lyuk?\n- ???\n- Afrikában.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mi a különbség a részeg és a nyuszika közt?\n- ???\n- A részeg kinyitja a sörét, a nyuszikát kinyírja a sörét.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mit mond a vak DJ?\n- ???\n- Nem látom a kezekeeeeet!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Miről ismered meg a buzi hóembert?\n- ???\n- A répa a seggében van.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mit mond a pedofil a MÁV pénztárnál?\n- ???\n- Egy diákot Pestig.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mit mond a pedofil mikor felkerül a mennybe?\n- ???\n- Hol van a kis Jézus?');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mi az: fehér és a sarkon áll?\n- ???\n- Kurvára esik a hó.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Hogy hívják az illatos cigányt?\n- ???\n- Aroma.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mi a közös a nőben és a gyufában?\n- ???\n-  Ha benedvesedik, akkor baszhatod!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mit csinál a cigány ha befejezi az egyetemet?\n- ???\n- Átmegy egy másik építkezésre!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mi az: Nyelve piros, szarva barna?\n- ???\n- Paradicsom.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mi az anyós mértékegysége?\n- ???\n- Megakurvaanyád.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mit vesz a halott a boltban?\n- ???\n- Élesztőt.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mi az? Két hulla úszik a vízen?\n- ???\n- Holtverseny.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mi az abszolút fajgyűlölet?\n- ???\n- Amikor a kopaszbarack veri a cigánymeggyet.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Mi a hasonlóság a cigány fiában és a borotvapengében?\n- ???\n- Mind a kettő Józsilett.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Hogy hívják a kávéfőző cigánygyereket?\n- ???\n- Jakobs a roma.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'IT','- Mi a női programozó rémálma?\n- ???\n- A végtelen ciklus.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'IT','- Mi a számítógépes szépségápolás?\n- ???\n- Átküldök neked egy giga bájt!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'IT','- Hol alszanak az álmos bitek?\n- ???\n- A hálókártyán.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'IT','- Miért nem csak ül a digit?\n- ???\n- Mert a digit áll is.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'IT','- Mit kavar fel két egymás mellett haladó nyomtató a sivatagban?\n- ???\n- Párhuzamos port.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'IT','- Melyik a leghosszabb hálózati kapcsolat?\n- ???\n- HoltodigLAN.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'IT','- Mi az: kicsi, sárga, de mégis nagy hatalma van?\n- ???\n- A root kiskacsa...');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'IT','- Mire táncolnak a programozók a bulin?\n- ???\n- Algoritmusra.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'IT','- Hol legelnek a Floppy-lemezek?\n- ???\n- Diszkréten...');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Mi lesz a sáskából ha megnő?\n- ???\n- Sás.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Ki tud magasabbra ugrani, mint egy felhőkarcoló?\n- ???\n- Mindenki, mert a felhőkarcolók nem tudnak ugrani!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Mit csinálnak a várvédők szabadidejükben?\n- ???\n- Elfoglalják magukat...');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Kőműves Kelemen ebédnél:\n- Egyél fiam anyád már fal!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Mit vet a kövér paraszt?\n- ???\n- Jó nagy árnyékot.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Hogyan hívják a liftet New Yorkban?\n- ???\n- Nyomógombbal.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Fehér, hideg és teljesen mozdulatlan, mi az?\n- ???\n- Hulla hó.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Mit csinál a depressziós vállfa?\n- ???\n- Felakasztja magát.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Miért nem lehet a járdán biciklizni?\n- ???\n- Mert nincs rajta pedál.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Hogyan lehet felismerni a kezdő tűzoltót?\n- ???\n- Elég könnyen...');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Akarsz sokat keresni?\n- Igen.\n- Akkor jól elbújok.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Mit kap a kis vidra ha ki jön a vízből?\n- ???\n- Levegőt.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Mit érez a katona, amikor látja hazájának zászlaját lobogni?\n- ???\n- A szelet.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Azt hallottad, hogy rájöttek a Loch Ness-i szörny titkára?\n- Nincs is neki titkára.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Miért kering a sas a hegy fölött?\n- ???\n- Mert alatta nem tud.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Hogy hívják a japán tűzoltót?\n- ???\n- Telefonon.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Mit söpörnek a reptéren?\n- ???\n- Airport.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Milyen gyapja marad a kis lámának a nyírás után?\n- ???\n- Nagyapja.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Min nevetnek a legtöbbet a cowboyok?\n- ???\n- Lóháton.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Minek megy a vak az erdőbe?\n- ???\n- Fának.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Két süteménytészta beszélget a kemencében:\n- Nagyon forró ez a kemence!\n- Ja! Már süti a hátam!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mi történne a pisai ferde toronnyal a Szaharában?\n- ???\n- Dűne.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mivel járnak a turisták Karthágó romjaihoz?\n- ???\n- Rombusszal.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Két egyiptomi a sivatag közepén:\n- Tevén ülsz?\n- Vénül ám az öreganyád!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mit csinál a norvég hajóskapitány, ha zsákutcába jut a hajója?\n- ???\n- Megfjordul.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miben különbözik Irán és egy porszívó?\n- ???\n- Az egyik perzsákkal van tele a másik porzsákkal.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Hogy kínálja áruját az olajsejk?\n- ???\n- Kő olaj?');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mit csinál a süket kalóz a telefonfülkében?\n- ???\n- Halóz.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miről lehet felismerni a mérges búvárt?\n- ???\n- Alig lát a pipától.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Hogy került a kezdő autóvezető lába a sütőbe?\n- ???\n- A barátai bíztatták, hogy nyugodtan taposson a gázba.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mi van a favágó szerszámoskamrájának ajtaján?\n- ???\n- Baltazár.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mit mond az, aki szánkó nélkül tér haza a szánkózásból?\n- ???\n- Szánom bánom!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Melyik a prémvadász kedvenc városa?\n- ???\n- Veszprém.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mondj egy tűzhányót, amelyik kimegy a divatból!\n- ???\n- Ela-vulkán.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért kell óvatosan kinyitni a Nemzeti Sportot?\n- ???\n- Hogy ki ne essen az Újpest.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért karikás az ördög szeme?\n- ???\n- Mert az ördög sohasem alszik.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Hogy hívják az afrikai tolvajt?\n- ???\n- Anti lop.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mi az: cukros és szobahőmérsékleten köt?\n- ???\n- Nagymama.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mi palacsinta ország fővárosa?\n- ???\n- Lekváros.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mire jött rá Józsi 6 év börtön után?\n- ???\n- Hogy nem is ő van bezárva, hanem az ajtó.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Hogy hívják a nincstelen titkosügynököt?\n- ???\n- Szegénykém.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mit csinál az űrjahós, ha megszomjazik?\n- ???\n- Űrkutat ás.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért buta a fa?\n- ???\n- Mert esze ágában sincs.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Melyek a legtétovább rovarok?\n- ???\n- A mitévő legyek.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mije van a birsalma fának?\n- ???\n- Birságai.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért adott fel apróhirdetést a légtornász?\n- ???\n- Mert elvesztette az egyensúlyát.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért nem rosszalkodik az iskolában a tulipánhagyma?\n- ???\n- Fél, hogy elültetik.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mit csinál a tolvaj ha nyaralni megy?\n- ???\n- Lopja a napot.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mi a hímzés ellenkezője?\n- ???\n- Nőzés.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mikor boldog az űrhajó?\n- ???\n- Az űr ha jó.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Hogyan kiáltott fel a zeneszerző amikor legújabb műve beleesett a forró vízbe?\n- ???\n- Forr a dalom!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért csípte ki magát a tehetségtelen festő?\n- ???\n- Mert azt mondták neki hogy jól fest öltönyben.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mi van a csempész arcán ha lebukik a határon?\n- ???\n- Vám pír.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miben különbözik egy kaktusz és egy nő?\n- ???\n- Egy kaktusz a sivatagban is nő, de egy nő a sivatagban sem kaktusz.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért nincs soha pénze a Jetinek?\n- ???\n- Túl nagy lábon él.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért nincs a mozdonyon bástya?\n- ???\n- Mert a vonat nem vár...');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért nem esett el soha Mozart a hajón?\n- ???\n- Mert hatéves kora óta tudott kompon állni.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mit csinál a bizonytalan tetoválóművész?\n- ???\n- Tétovál.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Milyenek lesznek az átfázott emberek a konyaktól?\n- ???\n- Mozgékonyak.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért nem lehet megbízni a villámban?\n- ???\n- Mert percenként akár százszor is becsaphat!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Honnan lehet felismerni a makkegészséges hegyet?\n- ???\n- Csúcsformában van.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért szereti a gumikötél a bungee jumpingot?\n- ???\n- Mert nem kell megszakadni a munkában.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Hogy tanul a gabonakereskedő?\n- ???\n- Bemagol mindent.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Miért nincs az ágyon Ű betű?\n- ???\n- Mert az ágyneműtartó!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Kit hívnak ha beleesik a vak a kútba?\n- ???\n- A vakmerőt.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'jean','- Jean, mi ez a dubörgés a szekrényben?\n- ???\n- Csak a ruhák mennek ki a divatból uram!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'jean','- Jean, vigye az ágyamat a padlásra!\n- Miért uram?\n- Mert fent szeretnék maradni.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'móricka','- Móriczka, mondj egy téli zöldséget!\n- Síparadicsom!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'móricka','- Móriczka, mit eszik az orángután?\n- ???\n- Még sosem ettem orangot, és tessék inkább tegezni Tanárnő!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'móricka','- Móriczka, ilyen piszkosan nem mehetsz az olimpiára!\n- De anyu, ez csak díszkosz.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'móricka','- Miért nem tanult meg Móriczka vízisízni?\n- ???\n- Mert nem talált lejtős tavat.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','- Miért ás a rendőr két gödröt?\n- ???\n- Mert az egyik túl kicsire sikerült.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','- Melyik a rendőr szúnyog?\n- ???\n- Amelyik nyakon csíp!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','- Hogyan fog a rendőr nyulat?\n- ???\n- Utánozza a répa hangját.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','- Miért megy a rendőr a fal mellett?\n- ???\n- Hogy körbe ne röhögjék.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','- Két rendőr közül melyik pisil távolabb?\n- ???\n- Amelyik előtte lehúzza a sliccét.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'blonde','- Hogy csinál a szőke nő lekvárt?\n- ???\n- Kinyomja a buktából.');
