-- Database changes for app version: 1.5

-- Fix grammar mistakes in joke texts
UPDATE jokes SET jokeText='Két szőke nő áll a patak két partján:\n- Segítesz átjutni a túlpartra?\n- De hiszen ott állsz!' WHERE jokeText='Két szőke nő áll a patak két partján:\n- Segítesz átjutni a túlpartra?\n- Dehiszen ott állsz!';
UPDATE jokes SET jokeText='Móricka hatalmas c betűket rajzol kishúgára mikor bejön az anyukája.\n- Hát te mit csinálsz Móricka a kishúgoddal?\n- Én semmit csak becézem!' WHERE jokeText='Móricka hatalmas c betűket rajzol kishugára mikor bejön az anyukája.\n- Hát te mit csinálsz Móricka a kishugoddal?\n- Én semmit csak becézem!';
UPDATE jokes SET jokeText='Két cigány gyalogol az úton. Egy kereszteződéshez érve meglátnak egy feszületet. Egyikük odafordul:\n- Dicsértessék!\nA társa megkérdezi:\n- Mi az tesó, ismered?\n-Há''mán hogyne! Hiszen ő adja mindennapi kenyerünket.\nMire a másik:\n- Mé, pék a csávó?' WHERE jokeText='Két cigány gyalogol az úton. Egy kereszteződéshez érve meglátnak egy feszületet. Egyikük odafordul:\n- Dícsértessék!\nA társa megkérdezi:\n- Mi az tesó, ismered?\n-Há''mán hogyne! Hiszen ő adja mindennapi kenyerünket.\nMire a másik:\n- Mé, pék a csávó?';
UPDATE jokes SET jokeText='- Mit vár a szőke nő a kád mellett?\n- ???\n- Hogy a meleg vizes csap jelzése végre zöldre váltson.' WHERE jokeText='- Mit vár a szőke nő a kád mellett?\n- ???\n- Hogy a melegvízes csap jelzése végre zöldre váltson.';
UPDATE jokes SET jokeText='- Mi van a macska fején?\n- ???\n- Cirmos cica haj.' WHERE jokeText='- Mi van a macske fején?\n- ???\n- Cirmos cica haj';
UPDATE jokes SET jokeText='- Hogy hívják a nincstelen titkos ügynököt?\n- ???\n- Szegénykém.' WHERE jokeText='- Hogy hívják a nincstelen titkosügynököt?\n- ???\n- Szegénykém.';
UPDATE jokes SET jokeText='A rendőr kint áll a szakadó esőben és a felesége által csomagolt szendvicset eszi.\nA kollégák döbbenten nézik:\n- Józsi, miért nem jössz be ide az őrszobára enni?\n- Azt mondta az asszony, akkor egyek, amikor jólesik.' WHERE jokeText='A rendőr kint áll a szakadó esőben és a felesége által csomagolt szendvicset eszi.\nA kollégák döbbenten nézik:\n- Józsi, miért nem jösz be ide az őrszobára enni?\n- Azt mondta az asszony, akkor egyek, amikor jólesik.';
UPDATE jokes SET jokeText='- Móricka, sorolj fel néhány állatot! - mondja a tanárnő az iskolában.\n- Kutyuska, tehénke, disznóka.\n- Jó, de nem kell mindig utána mondani a kicsinyítő képzőt!\n- Macs, kecs, csir, puly, szar.' WHERE jokeText='- Móricka, sorolj fel néhány állatot! - mondja a tanárnő az iskolában.\n- Kutyuska, tehénke, disznóka.\n- Jó, de nem kell mindig utána mondani a kicsinyítőképzőt!\n- Macs, kecs, csir, puly, szar.';
UPDATE jokes SET jokeText='- Miért nyalja a rendőr az óráját?\n- ???\n- Mert azt hallotta, hogy a Tic Tac frissíti a leheletét.' WHERE jokeText='- Miért nyalja a rendőr az óráját?\n- ???\n- Mert azt hallotta, hogy a Tic Tac frissíti a lehelletét.';
UPDATE jokes SET jokeText='A szőke nő kap a férjétől egy automata mosógépet. Másnap arra megy haza a férj hogy a felesége meztelenül rakja be a ruhákat a gépbe.\nMire a férj:\n- Mit csinálsz szívem?\n- Jaj drágám, a használati utasítás azt írta, hogy az első mosást ruha nélkül kell csinálni!' WHERE jokeText='A szőke nő kap a férjétől egy automata mosógépet. Másnap arra megy haza a férj hogy a felesége meztelenül rakja be a ruhákat a gépbe.\nMire a férj:\n- Mit csinálsz szivem?\n- Jaj drágám, a használati utasítás azt írta, hogy az első mosást ruha nélkül kell csinálni!';
UPDATE jokes SET jokeText='Lim és Lom mennek az erdőben.\nLom minden lépésnél ás egy í-t a földbe. Mennek tovább az erdőben, Lom pedig továbbra is ás. Egyszer csak Lim találkozik az erdésszel és megkérdezi tőle, mit csinál Lom.\nAz erdész gondolkodik egy kicsit, majd kiböki:\n- Társadalombiztosítás' WHERE jokeText='Lim és Lom mennek az erdőben.\nLom minden lépésnél ás egy í-t a földbe. Mennek tovább az erdőben, Lom pedig továbbra is ás. Egyszercsak Lim találkozik az erdésszel és megkérdezi tőle, mit csinál Lom.\nAz erdész gondolkodik egy kicsit, majd kiböki:\n- Társadalombiztosítás';
UPDATE jokes SET jokeText='- Két rendőr barkochbázik:\n- Lehet vele repülni? - kérdezi az első.\n- Hülye vagy, egy hamutartóval?' WHERE jokeText='- Két rendőr barchobázik:\n- Lehet vele repülni? - kérdezi az első.\n- Hülye vagy, egy hamutartóval?';

-- Add more jokes to the collection
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Mi a különbség a teológus és a geológus között?\n- ???\n- Ég és föld.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'anti','- Ki az abszolút szegény ember?\n- ???\n- Aki családfával tüzel.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','Két rendőrfeleség beszélget:\n- A férjem egy nagy csokor rózsát hozott haza... Estére megint tehetem szét a lábam.\nMire a másik:\n- Miért? Nincsen vázátok?');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','- Miért hord a rendőr vízipisztolyt magánál?\n- ???\n- Mert azt szeretné, ha a bűnöző nem úszná meg szárazon.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','- Miért tesz a rendőr egy teli és egy üres poharat az ágya mellé éjszakára?\n- ???\n- Mert vagy megszomjazik vagy nem.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','- Min vitatkozik 4 rendőr a személygépkocsiban?\n- ???\n- Hogy ki üljön az ablak mellé.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','- Miért teszi a rendőr a TV tetejére a kést?\n- ???\n- Hogy élesebb legyen a kép!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','Gyilkosságnál helyszínelnek a rendőrök. Az orvos megvizsgálja a holttestet, majd felnéz, és azt mondja:\nKifingott...\nMire az egyik rendőr:\n- Én, de mi köze ennek a bűnügyhöz?');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'cop','A rendőr elmegy a fényképészhez.\n- Mit parancsol, uram?\n- Egy filmet kérek...\n- 6x9?\n- Várjunk... 54.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'moricka','- Miért nem eszik Móricka reggelire banánt?\n- ???\n- Mert a banán déligyümölcs.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'moricka','Móricka anyja benyit a fürdőszobába, s azt látja, hogy a fia egy kád koromban fürdik.\n- Hát ezt miért csinálod? - kérdi megdöbbenve.\n- Mert mindig azt mondod, hogy nagy koromban jön meg az eszem!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'moricka','- Képzeld anyu, a buszon láttam István királyt!\n- Hogyhogy? Az nem lehet.\n- De igen! Egy öreg szakállas bácsi találkozott a barátjával és azt mondta neki: "Szervusz István, ezer éve nem láttalak!"');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Hogy hívják a villamosszék kistestvérét?\n- ???\n- Elektromos kisülés.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Miért nincs a süteménynek gyereke?\n- ???\n- Mert szétverték a tojásait.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'rough','- Miért tartóztatják le a drogot szedő papot?\n- ???\n- Szertartásért.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','Két részeg verekszik a rakparton. Arra megy egy rendőr:\n- Mi folyik itt? - kérdezi\n- Hát a Duna - feleli az egyik részeg.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','Pincér kérdezi a vendégtől:\n- Hogy ízlik a sült hús, uram?\n- Mint szakember megállapíthatom, hogy dicséretre méltó darab.\n- Ön szakács?\n- Nem, cipész...');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Láttad a mai újságot Lajos?\n- Nem. Miért, mi volt benne?\n- Az uzsonnám...');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Nagymama, mit ettél, hogy ilyen vörösek a szemeid?\n- ???\n- Hegesztettem!');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','Két elem beszélget:\n- De szép ruhád van, vetted?\n- Nem, anyám Varta.');
INSERT INTO jokes (isUsed, deliveryTime, type, jokeText) VALUES (0,null,'tiring','- Mit mond a csavar az ágyban?\n- ???\n- Még egy menet, és megszakadok.');

-- EOF
